apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: shukhratjon1201/accounts
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          value: accounts
        - name: SPRING_PROFILES_ACTIVE
          value: default
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://configserver:8071"
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        resources:
          limits:
            memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  type: NodePort
  selector:
    app: accounts
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
