apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: shukhratjon1201/configserver
        ports:
        - containerPort: 8071
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: git
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        resources:
          limits:
            memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  type: NodePort
  selector:
    app: configserver
  ports:
  - port: 8071
    targetPort: 8071
    nodePort: 30071
