x-network-deploy-service: &network-common-config
  networks:
    - bank-app
x-microservice-base: &microservice-base-config
  <<: *network-common-config
  deploy:
    resources:
      limits:
        memory: 700m
x-microservice-configserver-config: &microservice-configserver-conf
  <<: *microservice-base-config
  depends_on:
    configserver:
      condition: service_healthy
  environment:
    SPRING_PROFILES_ACTIVE: default
    SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"