version: "3.9"

x-network-deploy-service: &network-common-config
  networks:
    - bank-app
x-microservice-base: &microservice-base-config
  <<: *network-common-config
  deploy:
    resources:
      limits:
        memory: 700m
x-microservice-configserver-config: &microservice-configserver-conf
  <<: *microservice-base-config
  depends_on:
    configserver:
      condition: service_healthy
  environment:
    SPRING_PROFILES_ACTIVE: default
    SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
services:
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    <<: *network-common-config
  configserver:
    image: shukhratjon1201/configserver
    container_name: config_server_container
    environment:
      SPRING_PROFILES_ACTIVE: git
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    <<: *microservice-base-config
    depends_on:
      rabbitmq:
        condition: service_healthy
  accounts:
    image: shukhratjon1201/accounts
    container_name: account_container
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
    <<: *microservice-configserver-conf

  cards:
    image: shukhratjon1201/card
    container_name: card_container
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: cards
    <<: *microservice-configserver-conf

  loans:
    image: shukhratjon1201/loan
    container_name: loan_container
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
    <<: *microservice-configserver-conf
networks:
  bank-app:
    driver: "bridge"