server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: loan
  config:
#    import: "configserver:http://localhost:8071"
    import: "configserver:http://localhost:8071" # we can add optional property

  rabbitmq:
    host: ${SPRING_RABBIT_MQ_HOST}
    password: guest
    username: guest
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"