server:
  port: 8071
spring:
  application:
    name: "ConfigServer"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/futureSoftDev/AppConfig.git"
          default-label: main # branch
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    password: guest
    username: guest
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true